#!/usr/bin/python2.7
from default_rule import *

# === ADD your nftables ruleset below  here === ####
os.system("nft add rule ip filter " + ip + " accept")
# === ADD your nftables ruleset above here === ####
