#!/usr/bin/python2.7
from default_rule import *

# === ADD your nftables ruleset below  here === ####
ff_net = "{ 10.0.5.0/24, 10.0.0.0/24, 10.0.3.0/24 }"
os.system("nft add rule ip filter " + ip + " ip daddr ne" + ff_net  + " accept")
# === ADD your nftables ruleset above here === ####
